/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reesmcdevitt
 */
public class MainView extends javax.swing.JPanel {

    /**
     * Creates new form MainClass
     */
    private Database mainModel;
    private DefaultTableModel taskTableModel;
    private DefaultTableModel contactTableModel;
    private Object[] colTaskNames;
    private Object[] colContactNames;
    
    public MainView(Database mainModel)
    {
        this.mainModel = mainModel;
        initComponents();
        
        colTaskNames = new Object[4];
        colTaskNames[0] = "Task";
        colTaskNames[1] = "Due Date";
        colTaskNames[2] = "Type";
        colTaskNames[3] = "Description";
        
        colContactNames = new Object[5];
        colContactNames[0] = "Firstname";
        colContactNames[1] = "Lastname";
        colContactNames[2] = "Phone Number";
        colContactNames[3] = "Email";
        colContactNames[4] = "Address";
        
//        taskTableModel = new DefaultTableModel(mainModel.getTaskInfo(mainModel.getCurrentUserId()), colTaskNames); //Make Not Editable Model
//        taskTable.setModel(taskTableModel);
//        
//        contactTableModel = new DefaultTableModel(MainModel.getContactInfo(MainModel.getCurrentUserId()), colContactNames); //Make Not Editable Model
//        contactTable.setModel(contactTableModel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactTable = new javax.swing.JTable();
        contactLabel = new javax.swing.JLabel();
        taskLabel = new javax.swing.JLabel();

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(taskTable);

        contactTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(contactTable);

        contactLabel.setText("Contacts");

        taskLabel.setText("Tasks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskLabel)
                    .addComponent(contactLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(taskLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(contactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTable contactTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel taskLabel;
    private javax.swing.JTable taskTable;
    // End of variables declaration//GEN-END:variables
}
