/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import application.AddTask;
import application.Database;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author reesmcdevitt
 */
public class TaskView extends javax.swing.JPanel {

    /**
     * Creates new form TaskView
     */
    private Database taskModel;
    private AddTask addTask;
    private JScrollPane scrollPane;
    private JLabel test;
    private Object[] colNames;
    
    public TaskView(Database taskModel) 
    {
      
        
        this.taskModel = taskModel;
        
        addTask = new AddTask();
        
        initComponents();
        
        //Attempt to Populate JTable
        colNames = new Object[4];
        colNames[0] = "Task";
        colNames[1] = "Due Date";
        colNames[2] = "Type";
        colNames[3] = "Description";

        System.out.println(Arrays.deepToString(taskModel.getTaskInfo()));

        //Resets table data and colNames to it the ones we want - hard code to avoid XML problems
        DefaultTableModel model = new DefaultTableModel(taskModel.getTaskInfo(),colNames); //Make Not Editable Model
        testTable.setModel(model);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        testTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        testTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Task", "Due Date", "Type", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(testTable);
        if (testTable.getColumnModel().getColumnCount() > 0) {
            testTable.getColumnModel().getColumn(0).setMinWidth(1);
            testTable.getColumnModel().getColumn(0).setPreferredWidth(1);
            testTable.getColumnModel().getColumn(0).setHeaderValue("Task");
            testTable.getColumnModel().getColumn(1).setMinWidth(1);
            testTable.getColumnModel().getColumn(1).setPreferredWidth(2);
            testTable.getColumnModel().getColumn(1).setHeaderValue("Due Date");
            testTable.getColumnModel().getColumn(2).setMinWidth(1);
            testTable.getColumnModel().getColumn(2).setPreferredWidth(2);
            testTable.getColumnModel().getColumn(2).setHeaderValue("Type");
            testTable.getColumnModel().getColumn(3).setMinWidth(1);
            testTable.getColumnModel().getColumn(3).setPreferredWidth(3);
            testTable.getColumnModel().getColumn(3).setHeaderValue("Description");
        }

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");

        deleteButton.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addGap(50, 50, 50)
                        .addComponent(updateButton)
                        .addGap(50, 50, 50)
                        .addComponent(deleteButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    public void addAddButtonListener(ActionListener al)
    {
        addButton.addActionListener(al);
    }
    
    public void addUpdateButtonListener(ActionListener al)
    {
        updateButton.addActionListener(al);
    }
    
    public void addDeleteButtonListener(ActionListener al)
    {
        deleteButton.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable testTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the addTask
     */
    public AddTask getAddTask() {
        return addTask;
    }

    /**
     * @return the TaskTabel
     */
    public javax.swing.JTable getTaskTabel() {
        return testTable;
    }

    /**
     * @param TaskTabel the TaskTabel to set
     */
    public void setTaskTabel(javax.swing.JTable TaskTabel) {
        this.testTable = TaskTabel;
    }
}
